# Generated by Django 4.2.13 on 2024-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0003_remove_employee_user_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.CharField(choices=[('HR', 'HR'), ('Normal Employee', 'Normal Employee')], default='Normal Employee', max_length=15),
        ),
    ]
