# Generated by Django 4.2.10 on 2024-06-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0007_remove_employee_user_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
