# Generated by Django 4.2.10 on 2024-06-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0008_alter_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
    ]
