# Generated by Django 4.2.10 on 2024-06-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0010_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.CharField(choices=[('HR', 'HR'), ('Normal Employee', 'Normal Employee')], max_length=15),
        ),
    ]
